/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DDocIdIndexRouteImport } from './routes/d.$docId.index'
import { Route as DDocIdHistoryRouteImport } from './routes/d.$docId.history'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocIdIndexRoute = DDocIdIndexRouteImport.update({
  id: '/d/$docId/',
  path: '/d/$docId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocIdHistoryRoute = DDocIdHistoryRouteImport.update({
  id: '/d/$docId/history',
  path: '/d/$docId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/d/$docId/history': typeof DDocIdHistoryRoute
  '/d/$docId/': typeof DDocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/d/$docId/history': typeof DDocIdHistoryRoute
  '/d/$docId': typeof DDocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/d/$docId/history': typeof DDocIdHistoryRoute
  '/d/$docId/': typeof DDocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/device'
    | '/login'
    | '/settings'
    | '/invite/$token'
    | '/d/$docId/history'
    | '/d/$docId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/device'
    | '/login'
    | '/settings'
    | '/invite/$token'
    | '/d/$docId/history'
    | '/d/$docId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/device'
    | '/login'
    | '/settings'
    | '/invite/$token'
    | '/d/$docId/history'
    | '/d/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DDocIdHistoryRoute: typeof DDocIdHistoryRoute
  DDocIdIndexRoute: typeof DDocIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$docId/': {
      id: '/d/$docId/'
      path: '/d/$docId'
      fullPath: '/d/$docId/'
      preLoaderRoute: typeof DDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$docId/history': {
      id: '/d/$docId/history'
      path: '/d/$docId/history'
      fullPath: '/d/$docId/history'
      preLoaderRoute: typeof DDocIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  InviteTokenRoute: InviteTokenRoute,
  DDocIdHistoryRoute: DDocIdHistoryRoute,
  DDocIdIndexRoute: DDocIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
