// Embeds skills/glyphdown/SKILL.md (repo root) into src/skill-content.gen.ts
// so the bundled CLI can install the skill without network or repo access.
// Run via `pnpm gen:skill` after editing SKILL.md; the freshness test in
// test/install-skill.test.ts fails CI when the generated copy drifts.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const skillPath = join(pkgDir, '../../skills/glyphdown/SKILL.md')
const outPath = join(pkgDir, 'src/skill-content.gen.ts')

const skill = readFileSync(skillPath, 'utf8')

writeFileSync(
  outPath,
  `// GENERATED by scripts/gen-skill.mjs from skills/glyphdown/SKILL.md — do not edit.
// Re-generate with \`pnpm gen:skill\`; test/install-skill.test.ts guards freshness.

export const SKILL_MD: string = ${JSON.stringify(skill)}
`,
)
console.log(`gen-skill: embedded ${skill.length} bytes into src/skill-content.gen.ts`)
